services:
  db:
    image: postgres:13
    ports:
      - '5433:5432'
    container_name: clog_test_db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
volumes:
  postgres-data: